/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yiyi_providecodelib_CodeUtils */

#ifndef _Included_com_yiyi_providecodelib_CodeUtils
#define _Included_com_yiyi_providecodelib_CodeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yiyi_providecodelib_CodeUtils
 * Method:    getSign
 * Signature: (Ljava/util/Map;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yiyi_providecodelib_CodeUtils_getSign
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
